language: r
cache: packages
latex: false
fortran: false
pandoc: false

matrix:
  include:
    - dist: xenial
    - dist: xenial
      addons:
        apt:
          sources:
            - sourceline: 'ppa:cran/poppler'
          packages:
            - libwebp-dev
            - libpoppler-cpp-dev
            - poppler-data
            - libtesseract-dev
            - libleptonica-dev
            - tesseract-ocr-eng
    - dist: bionic
    - os: osx
      brew_packages: poppler || brew upgrade poppler
    - os: osx
      osx_image: 10.1
      disable_homebrew: true
      r_check_args: ""

addons:
  apt:
    packages:
      - libwebp-dev
      - libpoppler-cpp-dev
      - poppler-data
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
